[package]
name = "server"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = "0.4.5"
rocket_contrib = { version = "0.4.5", features = ["tera_templates"] }
structopt = "0.3.16"
chrono = "0.4.13"
